# Generated by Django 4.2.4 on 2023-08-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contenido',
        ),
    ]
