# Generated by Django 4.2.4 on 2023-08-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
